---
:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE: small
      - SNAP_VERSION: latest_build
        SNAP_OS: alpine
        TEST_TYPE: large
      - SNAP_VERSION: latest_build
        SNAP_OS: alpine
        TEST_TYPE: large
      - SNAP_VERSION: latest_build
        SNAP_OS: xenial
        TEST_TYPE: large
      - SNAP_VERSION: latest_build
        SNAP_OS: centos7
        TEST_TYPE: large
  matrix:
    exclude:
      - go: 1.6.3
        env: SNAP_VERSION=latest_build SNAP_OS=alpine TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest_build SNAP_OS=alpine TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest_build SNAP_OS=xenial TEST_TYPE=large
      - go: 1.6.3
        env: SNAP_VERSION=latest_build SNAP_OS=centos7 TEST_TYPE=large
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: OFcJ+8vV6CcUYMD+TUMsDUEudL8oD9MCM9HbfDg2BSSoYuuIIaN1G45BH0uV5tYfVlGQNd+Er5aEO7n7jxyu2eZuTofo/WhutFDmCcyFufzTn3p7GZGPcDHnI3PCi1FN+U+tHQ8V2vFdRll3TrZz9YpGFifRuzCa4oOcGfjBmQz9pU4K3cYFwsvO6sERiXVe+cED5wfO/7iMvnVS+QFqqwEV12k4+iM10zrzF6JRV28UL8fWRRhYAqXc2r8zSXl/VRxR6PfCFRQPWariPxD8MR5Lqo+4s6arrtGeOX9sETlLCILBrAJ5JYoEJEVfaHjzZSE2ecSeBIYUvQCALUH8FQD5Vlv6nf1fQAcpH1YmOqQct559ibv0Mk8K/+S/14Gba+SYgib6D/NC9g5NSYKrXfBo/+xfw42Iid/qlagXBaAxBXNw10Jaw7pa0eFz/4R5ruJ40/NA2vm+pYHIcewc3URxIjsCQrAhlRpXRRohB/grH0WWGDOwkZeMW9wGx8cVUhiScD6sibSNoAxEqAiSLxvVzy2N73/PnZxdqu/xJkaCUGCmlQkU6zv2RlxdSSU/eNU52wmGDxerlE9aoHfvbQML7XWPyw/vsLcsNtOG+cFd1lM3vWw9HpuKKgbGo8SRDRLaiWyEs11TsYz4ek1wom9a2pXgO2A6ZmuDAtiGHL4=
    api_key:
      secure: fVZ/wVGNcCLUDOGJld13wRs/CQYD5WvxWV3OsmqTj14CZsdNJlaYzl+nzKQHwcgaADuZS3z0oEuaCPIG3BGKUp3y65wKZqnZJZYpIrig/egQ7iSCJKVfrMWTgGtyzEcguSvgR11y9Dar5AfOoe0OdE0q+0MdesxwVDdjvHA4hCKR1fBNVkeYLJkgn9GWGkO3NYY3MDpTip+2EQ2L3kRaAbjJ/THwAnTB4AS0HFH04Iem+IzklvXJlAB8zXO/CssjbbhDZkYtnXxf9bRxSL1pMn+y4m+q50y2P643bSDdwSoxNkNkpuHC2DXiTblzJmgyAN/up2J5He9PmeGCLxOI/sO6LuKSAB5DBYKAQrgGBaEd9EQygvyPuZ1EnTFSH0/Dka2HWTlZZhHaMti8czqoOndqlkp7qysTqQczbnKSUhwBPj3DPMN4MRPcx4l5ZTFcJkIMfc0CoOnbgHeoTsvknBCfp843R4J2i5gJNBw7OO9xb7ILFztMI4VBaeMUzEnipSHcSYSrawyC6NxVfbI1oOmaWxVTOrKYzN0uwHYcc5AA5wmkkpIRdJiqOGGEOeYCh2qBmxZmsyuyVhcKFDgK070KiypbnFQEkP2eguRb+PingKBiEWKBshe3NsPYD09c8PKEbhB8fRWRo31QEXDLnKkQOUG/pgqVOn4GI3IGliw=
