# File managed by pluginsync
sudo: true
services: 
- docker
language: go
go:
- 1.6.3
- 1.7.3
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE: small
  - SNAP_VERSION: latest_build
    SNAP_OS: alpine
    TEST_TYPE: large
  - SNAP_VERSION: latest_build
    SNAP_OS: alpine
    TEST_TYPE: large
  - SNAP_VERSION: latest_build
    SNAP_OS: xenial
    TEST_TYPE: large
  - SNAP_VERSION: latest_build
    SNAP_OS: centos7
    TEST_TYPE: large
  - TEST_TYPE: build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
  - go: 1.6.3
    env: SNAP_VERSION=latest_build SNAP_OS=alpine TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest_build SNAP_OS=alpine TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest_build SNAP_OS=xenial TEST_TYPE=large
  - go: 1.6.3
    env: SNAP_VERSION=latest_build SNAP_OS=centos7 TEST_TYPE=large
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: OFcJ+8vV6CcUYMD+TUMsDUEudL8oD9MCM9HbfDg2BSSoYuuIIaN1G45BH0uV5tYfVlGQNd+Er5aEO7n7jxyu2eZuTofo/WhutFDmCcyFufzTn3p7GZGPcDHnI3PCi1FN+U+tHQ8V2vFdRll3TrZz9YpGFifRuzCa4oOcGfjBmQz9pU4K3cYFwsvO6sERiXVe+cED5wfO/7iMvnVS+QFqqwEV12k4+iM10zrzF6JRV28UL8fWRRhYAqXc2r8zSXl/VRxR6PfCFRQPWariPxD8MR5Lqo+4s6arrtGeOX9sETlLCILBrAJ5JYoEJEVfaHjzZSE2ecSeBIYUvQCALUH8FQD5Vlv6nf1fQAcpH1YmOqQct559ibv0Mk8K/+S/14Gba+SYgib6D/NC9g5NSYKrXfBo/+xfw42Iid/qlagXBaAxBXNw10Jaw7pa0eFz/4R5ruJ40/NA2vm+pYHIcewc3URxIjsCQrAhlRpXRRohB/grH0WWGDOwkZeMW9wGx8cVUhiScD6sibSNoAxEqAiSLxvVzy2N73/PnZxdqu/xJkaCUGCmlQkU6zv2RlxdSSU/eNU52wmGDxerlE9aoHfvbQML7XWPyw/vsLcsNtOG+cFd1lM3vWw9HpuKKgbGo8SRDRLaiWyEs11TsYz4ek1wom9a2pXgO2A6ZmuDAtiGHL4=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-statistics
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: OFcJ+8vV6CcUYMD+TUMsDUEudL8oD9MCM9HbfDg2BSSoYuuIIaN1G45BH0uV5tYfVlGQNd+Er5aEO7n7jxyu2eZuTofo/WhutFDmCcyFufzTn3p7GZGPcDHnI3PCi1FN+U+tHQ8V2vFdRll3TrZz9YpGFifRuzCa4oOcGfjBmQz9pU4K3cYFwsvO6sERiXVe+cED5wfO/7iMvnVS+QFqqwEV12k4+iM10zrzF6JRV28UL8fWRRhYAqXc2r8zSXl/VRxR6PfCFRQPWariPxD8MR5Lqo+4s6arrtGeOX9sETlLCILBrAJ5JYoEJEVfaHjzZSE2ecSeBIYUvQCALUH8FQD5Vlv6nf1fQAcpH1YmOqQct559ibv0Mk8K/+S/14Gba+SYgib6D/NC9g5NSYKrXfBo/+xfw42Iid/qlagXBaAxBXNw10Jaw7pa0eFz/4R5ruJ40/NA2vm+pYHIcewc3URxIjsCQrAhlRpXRRohB/grH0WWGDOwkZeMW9wGx8cVUhiScD6sibSNoAxEqAiSLxvVzy2N73/PnZxdqu/xJkaCUGCmlQkU6zv2RlxdSSU/eNU52wmGDxerlE9aoHfvbQML7XWPyw/vsLcsNtOG+cFd1lM3vWw9HpuKKgbGo8SRDRLaiWyEs11TsYz4ek1wom9a2pXgO2A6ZmuDAtiGHL4=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-processor-statistics
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: fVZ/wVGNcCLUDOGJld13wRs/CQYD5WvxWV3OsmqTj14CZsdNJlaYzl+nzKQHwcgaADuZS3z0oEuaCPIG3BGKUp3y65wKZqnZJZYpIrig/egQ7iSCJKVfrMWTgGtyzEcguSvgR11y9Dar5AfOoe0OdE0q+0MdesxwVDdjvHA4hCKR1fBNVkeYLJkgn9GWGkO3NYY3MDpTip+2EQ2L3kRaAbjJ/THwAnTB4AS0HFH04Iem+IzklvXJlAB8zXO/CssjbbhDZkYtnXxf9bRxSL1pMn+y4m+q50y2P643bSDdwSoxNkNkpuHC2DXiTblzJmgyAN/up2J5He9PmeGCLxOI/sO6LuKSAB5DBYKAQrgGBaEd9EQygvyPuZ1EnTFSH0/Dka2HWTlZZhHaMti8czqoOndqlkp7qysTqQczbnKSUhwBPj3DPMN4MRPcx4l5ZTFcJkIMfc0CoOnbgHeoTsvknBCfp843R4J2i5gJNBw7OO9xb7ILFztMI4VBaeMUzEnipSHcSYSrawyC6NxVfbI1oOmaWxVTOrKYzN0uwHYcc5AA5wmkkpIRdJiqOGGEOeYCh2qBmxZmsyuyVhcKFDgK070KiypbnFQEkP2eguRb+PingKBiEWKBshe3NsPYD09c8PKEbhB8fRWRo31QEXDLnKkQOUG/pgqVOn4GI3IGliw=
  file:
    - release/snap-plugin-processor-statistics_linux_x86_64
    - release/snap-plugin-processor-statistics_darwin_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-processor-statistics
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"